# dist/<target>/ — same convention as Sample / libmcp2221a_hid.
# Nested override: ESPLORA_HID_DIST_ROOT, else FOUNDATION_DIST_ROOT.
if(DEFINED ESPLORA_HID_DIST_ROOT)
    set(ESPLORA_HID_DIST_ROOT "${ESPLORA_HID_DIST_ROOT}")
elseif(DEFINED FOUNDATION_DIST_ROOT)
    set(ESPLORA_HID_DIST_ROOT "${FOUNDATION_DIST_ROOT}")
else()
    if(DEFINED ENV{BUILD_TARGET} AND NOT "$ENV{BUILD_TARGET}" STREQUAL "")
        set(_ESP_DIST_TARGET "$ENV{BUILD_TARGET}")
    elseif(CMAKE_TOOLCHAIN_FILE MATCHES "mingw64")
        set(_ESP_DIST_TARGET "mingw64")
    elseif(WIN32 AND CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        set(_ESP_DIST_TARGET "mingw64")
    elseif(MSVC)
        if(CMAKE_SIZEOF_VOID_P EQUAL 8)
            set(_ESP_DIST_TARGET "msvc${MSVC_VERSION}-x86_64")
        else()
            set(_ESP_DIST_TARGET "msvc${MSVC_VERSION}-x86")
        endif()
    elseif(UNIX AND NOT APPLE)
        set(_ESP_DIST_TARGET "linux-x86_64-unknown")
    else()
        set(_ESP_DIST_TARGET "unknown")
    endif()
    set(ESPLORA_HID_DIST_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/dist/${_ESP_DIST_TARGET}")
endif()

message(STATUS "ESPLORA_HID_DIST_ROOT: ${ESPLORA_HID_DIST_ROOT}")
